[train.backend]
name = "decent_dp"
topology = "complete"
adaptive_consensus_omega = 0.0
adaptive_consensus_p = 3.0

[train.optim]
name = "accumadam"
accum_iters = 4
lr = 0.0008
betas = [0.9, 0.999]

[train]
use_amp = true